# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[41,)"
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
showAsResourcePack=false

[[mods]]
modId="elements"
version="1.0.0.0"
displayName="Minecraft Minero"
updateJSONURL=""
displayURL=""
logoFile=""
credits="Si hay que ser minero, romper con pico en el hierro, no importa creeper que venga pa que sepas que te quiero"
authors="Carolina Arellano, Yochabel Martinez and Rodrigo Lopez"
description='''
    This project is created to the Objects Oriented Programming Class
    The main purpose is using the structure of Java to give a tool to the developers of Minecraft Mods to create their armours, weapons and poisons easily!
    Enjoy the final product !!!
'''
displayTest = "MATCH_VERSION"

[[dependencies.elements]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.elements]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
